CXX=g++
DIR=../bin/

all:
	$(CXX) noop.cpp -o $(DIR)noop
	$(CXX) delayedremovetag.cpp -o $(DIR)delayedremovetag
	$(CXX) number.cpp -o $(DIR)number
	$(CXX) removetag.cpp -o $(DIR)removetag
	$(CXX) removetag0.cpp -o $(DIR)removetag0

clean:
	rm -f noop delayedremovetag number removetag removetag0